// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextDirection } from "./TextDirection";

/**
 * Configuration options which are specific to the book and required for
 * loading it from disk.
 */
export type BookConfig = {
  /**
   * The book's title.
   */
  title: string | null;
  /**
   * The book's authors.
   */
  authors: Array<string>;
  /**
   * An optional description for the book.
   */
  description: string | null;
  /**
   * Location of the book source relative to the book's root directory.
   */
  src: string;
  /**
   * Does this book support more than one language?
   */
  multilingual: boolean;
  /**
   * The main language of the book.
   */
  language: string | null;
  /**
   * The direction of text in the book: Left-to-right (LTR) or Right-to-left (RTL).
   * When not specified, the text direction is derived from [`BookConfig::language`].
   */
  "text-direction": TextDirection | null;
};
