// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chapter } from "./Chapter";

/**
 * Enum representing any type of item which can be added to a book.
 */
export type BookItem =
  | { Chapter: Chapter }
  | "Separator"
  | { PartTitle: string };
