// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Configuration for the build procedure.
 */
export type BuildConfig = {
  /**
   * Where to put built artefacts relative to the book's root directory.
   */
  "build-dir": string;
  /**
   * Should non-existent markdown files specified in `SUMMARY.md` be created
   * if they don't exist?
   */
  "create-missing": boolean;
  /**
   * Should the default preprocessors always be used when they are
   * compatible with the renderer?
   */
  "use-default-preprocessors": boolean;
  /**
   * Extra directories to trigger rebuild when watching/serving
   */
  "extra-watch-dirs": Array<string>;
};
