// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookConfig } from "./BookConfig";
import type { BuildConfig } from "./BuildConfig";
import type { RustConfig } from "./RustConfig";

/**
 * The overall configuration object for MDBook, essentially an in-memory
 * representation of `book.toml`.
 */
export type Config = {
  /**
   * Metadata about the book.
   */
  book: BookConfig;
  /**
   * Information about the build environment.
   */
  build: BuildConfig;
  /**
   * Information about Rust language support.
   */
  rust: RustConfig;
};
