// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Book } from "./Book";
import type { Config } from "./Config";

/**
 * The context provided to all renderers.
 */
export type RenderContext = {
  /**
   * Which version of `mdbook` did this come from (as written in `mdbook`'s
   * `Cargo.toml`). Useful if you know the renderer is only compatible with
   * certain versions of `mdbook`.
   */
  version: string;
  /**
   * The book's root directory.
   */
  root: string;
  /**
   * A loaded representation of the book itself.
   */
  book: Book;
  /**
   * The loaded configuration file.
   */
  config: Config;
  /**
   * Where the renderer *must* put any build artefacts generated. To allow
   * renderers to cache intermediate results, this directory is not
   * guaranteed to be empty or even exist.
   */
  destination: string;
};
