// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Rust edition to use for the code.
 */
export type RustEdition = "2024" | "2021" | "2018" | "2015";
