// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RustEdition } from "./RustEdition";

/**
 * Configuration for the Rust compiler(e.g., for playground)
 */
export type RustConfig = {
  /**
   * Rust edition used in playground
   */
  edition: RustEdition | null;
};
