// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A section number like "1.2.3", basically just a newtype'd `Vec<u32>` with
 * a pretty `Display` impl.
 */
export type SectionNumber = Array<number>;
