// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Text direction to use for HTML output
 */
export type TextDirection = "ltr" | "rtl";
